### ISSUE TITLE
Daemon not starting after upgrading to 0.6.1, openelec + rp2

### ISSUE THREAD

**Issue by jccardenas5** [steeve/plugin.video.pulsar#144]
Hi,
After upgrading from pulsar 0.5, to 0.6.1, now the pulsar daemon doesn't start at boot, so the plugin can not open. I'm on a raspberry pi 2 with OpenElec 5.0.8
My log is as follows:

12:00:37 T:1627386944  NOTICE: [plugin.video.pulsar] pulsar: starting jsonrpc service
12:00:37 T:1618998336  NOTICE: [plugin.video.pulsar] pulsard: starting pulsard
12:00:38 T:1763456064  NOTICE:  StorageServer Module loaded RUN
12:00:38 T:1763456064  NOTICE: StorageClient-2.5.4 Starting server
12:00:40 T:1805399104  NOTICE: script.grab.fanart: Grab Fanart Service Started
12:00:40 T:1618998336  NOTICE: Traceback (most recent call last):
12:00:40 T:1618998336  NOTICE:   File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 129, in pulsard_thread
12:00:40 T:1618998336  NOTICE:     proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
12:00:40 T:1618998336  NOTICE:   File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 100, in start_pulsard
12:00:40 T:1618998336  NOTICE:     pulsar_dir, pulsar_binary = get_pulsar_binary()
12:00:40 T:1618998336  NOTICE:   File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 67, in get_pulsar_binary
12:00:40 T:1618998336  NOTICE:     if not os.path.exists(dest_binary_path) or get_pulsard_checksum(dest_binary_path) != get_pulsard_checksum(binary_path):
12:00:40 T:1618998336  NOTICE:   File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 35, in get_pulsard_checksum
12:00:40 T:1618998336  NOTICE:     with open(path) as fp:
12:00:40 T:1618998336  NOTICE: IOError: [Errno 2] No such file or directory: u'/storage/.kodi/addons/plugin.video.pulsar/resources/bin/linux_arm/pulsar'
12:00:40 T:1618998336   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 504, in run
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 129, in pulsard_thread
                                                proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 100, in start_pulsard
                                                pulsar_dir, pulsar_binary = get_pulsar_binary()
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 67, in get_pulsar_binary
                                                if not os.path.exists(dest_binary_path) or get_pulsard_checksum(dest_binary_path) != get_pulsard_checksum(binary_path):
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 35, in get_pulsard_checksum
                                                with open(path) as fp:
                                            IOError: [Errno 2] No such file or directory: u'/storage/.kodi/addons/plugin.video.pulsar/resources/bin/linux_arm/pulsar'
12:00:52 T:1595929664  NOTICE: Thread BackgroundLoader start, auto delete: false
12:00:56 T:1595929664  NOTICE: Thread LanguageInvoker start, auto delete: false
12:00:57 T:1595929664  NOTICE: -->Python Interpreter Initialized<--
12:00:57 T:1969790976   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/
12:00:57 T:1969790976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
12:00:57 T:1595929664  NOTICE: Thread BackgroundLoader start, auto delete: false
12:10:42 T:1736438848  NOTICE: Thread JobWorker start, auto delete: true

 Hope it can help find the bug, thank you!

**Comment by erik360** [comment]
Try uninstalling and reinstalling, with reboots in between. I cleared out the downloaded package as well to be sure. It then started up for me. OSMC + RPi2.

**Comment by Renive** [comment]
I also have a loop with prompt to restart. Both remote controls checked. Those lines in log are weird as hell. (previously, Pulsar worked)

15:48:58 T:2336   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
15:48:58 T:2336   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pulsar/
15:48:58 T:2336   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
15:48:58 T:2336   DEBUG: CGUIMediaWindow::GetDirectory ()
15:48:58 T:2336   DEBUG:   ParentPath = [plugin://plugin.video.pulsar/]
15:48:58 T:176  NOTICE: Thread BackgroundLoader start, auto delete: false
15:48:58 T:176   DEBUG: Thread BackgroundLoader 176 terminating

Reinstalling Pulsar doesn't help. Don't know what caused the issue, since last working Pulsar I upgraded to Isengard beta 2 (from 14.2), changed skin to Titan and deleted few orphaned parenthesis.

**Comment by Renive** [comment]
Nevermind, deleting pulsar from addon_data folder and reinstalling helped. Transition to 0.6.1 is kinda rough because new cache are totally different in structure.

**Comment by shuvro68** [comment]
Hi! i just install pulsar v0.6.1 for android. it say to restart Kodi. i restart several time but still Not opening.
Allways saying restart kodi any fix bro ??

**Comment by jccardenas5** [comment]
Thank you for your suggestions, looks that the package downloaded when upgrading via repo was corrupt or something like that, I uninstalled, removed the package, and downloaded the zip directly from here, Installed from zip and it worked, so problem solved now!

**Comment by calventeramirez** [comment]
I will not start Pulsar and can not be done, reboot, erase all, reinstall the system, but still started either to start the OpenELEC

Please HELP!!!!!

**Comment by jokoast** [comment]
Instead of cloning the git itself, use the download to zip, the zip in the git is broken.

**Comment by calventeramirez** [comment]
i download this zip and don´t start with openelec

**Comment by jokoast** [comment]
Hmm, i thought it was the same problem as i had.
No idea of the solution, so.

**Comment by alturron** [comment]
just found this to work in linux 64bits (dunno why bin and its subdirs and binaries are missing?)
mkir -p $HOME/.kodi/plugin.video.pulsar/resources/bin/linux_x64
download 3.7MB pulsar from http://mxrtv.uk/mxrtv-repo/plugin.video.pulsar/resources/bin/linux_x64/ into newly made directory and start kodi

**Comment by welwisher101** [comment]
deleting pulsar from addon_data folder and reinstalling worked! in windows this addon_data is under C:\Users\user_name\AppData\Roaming\Kodi\userdata\addon_data

**Comment by maverick1960** [comment]
After installing pulsar plugin on my minix the add on crashed then kept on restarting. Rebooting did not help as I got same error message then somehow became okay and after installing repo everything works fine. Wonder what happened
