### ISSUE TITLE
Must Restart XBMC

### ISSUE THREAD

**Issue by xbmchappy** [steeve/plugin.video.pulsar#146]
I have a windows pc with Kodi installed. After auto-updating, pulsar stopped working.
Everytime i try to use, it says must restart xbmc. 
I have cleared the addons folder, and reinstalled kodi, and the problem persists.

**Comment by Renive** [comment]
Delete userdata/addons_data/pulsar (something like that). Cache is a problem.

**Comment by triptec** [comment]
I have the same problem and I've tried uninstall, remove  ~/.kodi/userdata/addon_data/plugin.video.pulsar, one thing that seemed a bit strange to me was that ~/.kodi/userdata/addon_data/plugin.video.pulsar/bin was empty, using raspberry 2, xbian

**Comment by jokoast** [comment]
Instead of cloning the git itself, use the download to zip, the zip in the git is broken.

**Comment by jotalezameta** [comment]
hey guys I been looking all over internet to fix this problem...no luck, I have windows 8(its a gamer pc) a month a go pulsar was working, now just appears restart xbmc,

**Comment by jotalezameta** [comment]
I try a couple times to uninstall kodi, I mean start from scratch but I still having the same problem...I have a laptop with windows 7 no problems there...I need help guys!!!!

**Comment by patadn** [comment]
Hi 
I have the same problem , 
Did you found the solution

**Comment by jokoast** [comment]
Have you try to dl it from https://github.com/steeve/plugin.video.pulsar/releases ? Because i had the same issue when i cloned the git and used the zip inside.

**Comment by swm93** [comment]
I was able to resolve this issue by disabling the HTTP sever. Not sure if this will work for anyone else; however, there seems to be a conflict between the two in my case.

**Comment by cofre** [comment]
Hello all!
My  Solution!!!

I had same issue after installing for first time version 0.6.1, saying reboot needed for XBMC.
After a few tries, suddenly a windows firewall windows appears to allow "pulsar.exe" (for the second time, first one was inmediatle open the app after installation)

Seems like something related to the firewalls make this issue.

By now, problem is solved. Hope it helps for you. Good luck

**Comment by marianojhb** [comment]
Hello!

I am stuck with the same problem.

I run a Fire Amazon Fire TV. I could install Pulse but I got the same message: XBMC must restart. Of course I did that but nothing seems to change. As it is Android, I don't know where to find the firewall issue as cofre mentions.

Any clue? Thank you MB

**Comment by Gotcha007** [comment]
Same here with Nvidia Shield Kodi 16.0

**Comment by dolezsa** [comment]
```
022-09-01 02:24:48.081 T:3534680960  NOTICE: [plugin.video.pulsar] pulsard: starting pulsard
2022-09-01 02:24:48.491 T:3534680960  NOTICE: [plugin.video.pulsar] Deleting stale files set([])
2022-09-01 02:24:49.068 T:3534680960   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in 
__bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in 
run
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resou
rces/site-packages/pulsar/daemon.py", line 129, in pulsard_thread
                                                proc = start_pulsard(stdout=subprocess.PIPE, stderr
=subprocess.STDOUT)
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resou
rces/site-packages/pulsar/daemon.py", line 114, in start_pulsard
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in
 __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1047, i
n _execute_child
                                            OSError: [Errno 8] Exec format error
```

**Comment by dolezsa** [comment]
```
2022-09-01 02:42:58.314 T:3553432448  NOTICE: [plugin.video.pulsar] pulsar: starting jsonrpc service
2022-09-01 02:42:58.347 T:3545039744  NOTICE: [plugin.video.pulsar] pulsard: starting pulsard
2022-09-01 02:43:01.445 T:3545039744  NOTICE: [plugin.video.pulsar] Deleting stale files set([])
2022-09-01 02:43:01.762 T:3545039744   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 129, in pulsard_thread
                                                proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 114, in start_pulsard
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                            OSError: [Errno 8] Exec format error
2022-09-01 02:43:04.323 T:3484324736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.pulsar/navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 64, in run
                                                data = _json(url)
                                              File "/storage/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 43, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
2022-09-01 02:43:04.494 T:3505386368   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/
2022-09-01 02:43:04.498 T:4058398144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
```
