### ISSUE TITLE
subtitles issue on android

### ISSUE THREAD

**Issue by bar333** [steeve/plugin.video.pulsar#150]
when i try to use pulsar subtitles - it finds the right subs...but when i choose them - it gives me an error - script failed - it doesn't happen with any other subs addon...only with pulsar subs...everything works fine on genesis for example...

**Comment by aiguanachein** [comment]
same in my rpi2 with openelec 5.08

**Comment by sh00le** [comment]
This is log from vidon-xbmc app:

23:29:34 T:1923892112  NOTICE: Thread LanguageInvoker start, auto delete: false
23:29:34 T:1923892112  NOTICE: -->Python Interpreter Initialized<--
23:29:34 T:1923892112  NOTICE: http://localhost:65251/?action=search&languages=Croatian%2cEnglish%20(US)%2cSerbian&preferredlanguage=Croatian
23:29:36 T:1855700424  NOTICE: [plugin.video.pulsar] [GIN] 2015/07/28 - 21:29:35 |[97;42m 200 [0m|     1.170651s | 127.0.0.1:58612 |[97;44m  [0m GET     /
23:29:42 T:1861457880  NOTICE: Thread LanguageInvoker start, auto delete: false
23:29:42 T:1861457880  NOTICE: -->Python Interpreter Initialized<--
23:29:42 T:1861457880  NOTICE: http://localhost:65251/subtitle/1954168033?action=download&dl=http%3a%2f%2fdl.opensubtitles.org%2fen%2fdownload%2ffilead%2fsrc-api%2fvrf-ad4946addb%2fsid-psoisn23539tvl8214g2tqndl5%2f1954168033.gz&file=The.Wolf.of.Wall.Street.2013.720p.BluRay.X264-AMIABLE.srt&fmt=srt&lang=eng
23:29:42 T:1861457880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 500: Internal Server Error
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.vidonme.xbmc/files/.xbmc/addons/plugin.video.pulsar/navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "/storage/emulated/0/Android/data/org.vidonme.xbmc/files/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 64, in run
                                                data = _json(url)
                                              File "/storage/emulated/0/Android/data/org.vidonme.xbmc/files/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 43, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 397, in open
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 435, in error
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/goland/vbox1/vidon-xbmc/vidon-kodi/build/helix/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 500: Internal Server Error
                                            -->End of Python script error report<--
23:29:42 T:1861605440   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.pulsar/subtitle/1954168033?action=download&dl=http%3a%2f%2fdl.opensubtitles.org%2fen%2fdownload%2ffilead%2fsrc-api%2fvrf-ad4946addb%2fsid-psoisn23539tvl8214g2tqndl5%2f1954168033.gz&file=The.Wolf.of.Wall.Street.2013.720p.BluRay.X264-AMIABLE.srt&fmt=srt&lang=eng
23:29:42 T:1855700424  NOTICE: [plugin.video.pulsar] [GIN] 2015/07/28 - 21:29:42 |[97;41m 500 [0m|     214.401ms | 127.0.0.1:58623 |[97;44m  [0m GET     /subtitle/1954168033
23:29:42 T:1855700424  NOTICE: [plugin.video.pulsar] Error #01: open /data/local/tmp/566920854: permission denied
23:39:26 T:1855700424  NOTICE: [plugin.video.pulsar] 2015-07-28 21:39:26  NOTI  libtorrent       external_ip_alert: external IP received: xxx.xxx.xx.xxx

**Comment by vitorma** [comment]
A workaround is root your device and add write permission to others on /data/local/tmp/ folder
