### ISSUE TITLE
Pulsar Daemon not starting after upgrading to Kodi 15.x (ver 0.6.1)

### ISSUE THREAD

**Issue by rainmanone** [steeve/plugin.video.pulsar#168]
weird problem,
for some obscure reason I just can't get Pulsar to work on Kodi 15.0,15.1 or even 16.
no problems with 14.2
I'm on the latest rev (0.6.1) 
My system is: Celeron j1900, windows 8.1 64 bit (bing edition), 
When upgrading from kodi 14.2 --> I get an error (in the log) that there's a problem connecting to remote machine.
if I do a clean install of Kodi (and install Pulsar only), I'm just getting a request to restart XBMC before using Pulsar (and it doesn't help, I keep getting the request after restart too).

I see that pulsar.exe process is running in the Task Manager, but the notification about the Pulsar Daemon start never pops up.

any ideas how to debug it ?

**Comment by rainmanone** [comment]
00:25:11 T:2832  NOTICE: Thread LanguageInvoker start, auto delete: false
00:25:11 T:3560   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
00:25:11 T:2832  NOTICE: -->Python Interpreter Initialized<--
00:25:11 T:2832  NOTICE: http://localhost:65251/
00:25:13 T:2832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            Traceback (most recent call last):
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\resources\site-packages\pulsar\navigation.py", line 64, in run
                                                data = _json(url)
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\resources\site-packages\pulsar\navigation.py", line 43, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(_args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1214, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            -->End of Python script error report<--
00:25:13 T:3560   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pulsar/
00:25:13 T:3560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
00:25:13 T:3816  NOTICE: Thread BackgroundLoader start, auto delete: false
00:25:29 T:2592  NOTICE: Thread LanguageInvoker start, auto delete: false
00:25:29 T:3560   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
00:25:29 T:2592  NOTICE: -->Python Interpreter Initialized<--
00:25:29 T:2592  NOTICE: http://localhost:65251/
00:25:31 T:2592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            Traceback (most recent call last):
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\resources\site-packages\pulsar\navigation.py", line 64, in run
                                                data = _json(url)
                                              File "C:\Users\raana_000\AppData\Roaming\Kodi\addons\plugin.video.pulsar\resources\site-packages\pulsar\navigation.py", line 43, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(_args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1214, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            -->End of Python script error report<--
00:25:31 T:3560   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pulsar/
00:25:31 T:3560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
00:25:31 T:664  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by rainmanone** [comment]
00:25:13 T:2832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
                                            Traceback (most recent call last):

**Comment by rainmanone** [comment]
Error Contents: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

**Comment by rainmanone** [comment]
Hi, 

look like the problem is "solved"
changing the HTTP remote control port in Kodi back to the default 80 (it was set previously to 9090), allowed the Pulsar Daemon to load, and now it's working properly.
(every other port causes a connection fail).
so.. it's a workaround, but it works
(it doesn't happen in Kodi 14.2 though, no problem changing the port there)
