### ISSUE TITLE
crash's on trying any listing option

### ISSUE THREAD

**Issue by rudamaia** [steeve/plugin.video.pulsar#211]
raspberry B+
OSMC 2016.01-1
plugin.video.pulsar-0.6.1

22:29:21 275.007202 T:2650199072  NOTICE: [plugin.video.pulsar] pulsard: starting pulsard
22:29:21 275.038574 T:2705323040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pulsar/navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 64, in run
                                                data = _json(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 43, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 415, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
                                                raise BadStatusLine(line)
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
22:29:21 275.054749 T:2650199072  NOTICE: [plugin.video.pulsar] Deleting stale files set([])
22:29:22 275.698181 T:3024859696   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/movies/popular
22:29:22 275.718781 T:3024859696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/movies/popular) failed

**Comment by rudamaia** [comment]
tried again using version 0.5.0, same crash.

**Comment by IVXCVI** [comment]
I'm having the same issue in OpenElec. It appears Pulsar is finally dead. I'll be trying out Quasar on my system tonight to see if it's a full replacement.

https://github.com/scakemyer/plugin.video.quasar

**Comment by vidje** [comment]
got the same issue, version 0.7

log: http://xbmclogs.com/peutwwk96

**Comment by XayOn** [comment]
Interesting, seems like pulsar is going against a specific thetvdb endpoint wich is returning 404s

**Comment by XayOn** [comment]
Oh, didn't see that this is no longer mantained. Sorry.

**Comment by mehdicopter** [comment]
Any news ? Because the error is still there.. Can't browse movies nor tv shows...

**Comment by XayOn** [comment]
Use quassar, this is  no longer mantained

**Comment by mehdicopter** [comment]
Thanks I just understood your last comment :)
