### ISSUE TITLE
pulsar wont start after uopgrade to 0.4.2

### ISSUE THREAD

**Issue by ramonskie** [steeve/plugin.video.pulsar#78]
since the automatic upgrade from 0.4.1 to 0.4.2 i get the message
that i need to restart xbmc to start pulsar
i have already done this several times
and the error below is a snippet from xbmc.log

hardware: cubox-i4pro
os: xbian 1.0rc3
kernel: 3.14.27+

```
23:24:16 T:1370846128  NOTICE: [plugin.video.pulsar] pulsard: starting pulsard
23:24:16 T:1386214320  NOTICE: [plugin.video.pulsar] pulsar: starting jsonrpc service
23:24:16 T:1370846128  NOTICE: Traceback (most recent call last):
23:24:16 T:1370846128  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 104, in pulsard_thread
23:24:16 T:1370846128  NOTICE:     proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
23:24:16 T:1370846128  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 81, in start_pulsard
23:24:16 T:1370846128  NOTICE:     pulsar_dir, pulsar_binary = get_pulsar_binary()
23:24:16 T:1370846128  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 59, in get_pulsar_binary
23:24:16 T:1370846128  NOTICE:     if not os.path.exists(dest_binary_path) or get_pulsard_checksum(dest_binary_path) != get_pulsard_checksum(binary_path):
23:24:16 T:1370846128  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 34, in get_pulsard_checksum
23:24:16 T:1370846128  NOTICE:     with open(path) as fp:
23:24:16 T:1370846128  NOTICE: IOError: [Errno 2] No such file or directory: '/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/bin/linux_arm/pulsar'
23:24:16 T:1370846128   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 104, in pulsard_thread
                                                proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 81, in start_pulsard
                                                pulsar_dir, pulsar_binary = get_pulsar_binary()
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 59, in get_pulsar_binary
                                                if not os.path.exists(dest_binary_path) or get_pulsard_checksum(dest_binary_path) != get_pulsard_checksum(binary_path):
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 34, in get_pulsard_checksum
                                                with open(path) as fp:
                                            IOError: [Errno 2] No such file or directory: '/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/bin/linux_arm/pulsar'
23:24:17 T:1540629424  NOTICE: XBian : upgrade service started
23:25:35 T:1480950704  NOTICE: Thread JobWorker start, auto delete: true
```

**Comment by ramonskie** [comment]
locate pulsar binary in a different directory

/home/xbian/.xbmc/userdata/addon_data/plugin.video.pulsar/bin/linux_arm/pulsar

**Comment by steeve** [comment]
Your install is corrupted. Try reinstalling from the zip file in the releases page.

**Comment by ramonskie** [comment]
delete the addon and removed all directories related to pulsar in .xbmc/addon/ and .xbmc/userdata/
and reinstalled via repo
this resulted in the same error every time

then i tried to install the zip from the release page
and this resulted in a different error

```
11:23:39 T:1335747504  NOTICE: Traceback (most recent call last):
11:23:39 T:1335747504  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 104, in pulsard_thread
11:23:39 T:1335747504  NOTICE:     proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
11:23:39 T:1335747504  NOTICE:   File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 89, in start_pulsard
11:23:39 T:1335747504  NOTICE:     return subprocess.Popen(args, **kwargs)
11:23:39 T:1335747504  NOTICE:   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
11:23:39 T:1335747504  NOTICE:     errread, errwrite)
11:23:39 T:1335747504  NOTICE:   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
11:23:39 T:1335747504  NOTICE:     raise child_exception
11:23:39 T:1335747504  NOTICE: OSError: [Errno 26] Text file busy
11:23:39 T:1335747504   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 104, in pulsard_thread
                                                proc = start_pulsard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/xbian/.xbmc/addons/plugin.video.pulsar/resources/site-packages/pulsar/daemon.py", line 89, in start_pulsard
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 26] Text file busy
11:23:43 T:1312920496  NOTICE: Thread BackgroundLoader start, auto delete: false
11:24:08 T:1312920496  NOTICE: Previous line repeats 1 times.
11:24:08 T:1312920496  NOTICE: Thread LanguageInvoker start, auto delete: false
11:24:08 T:1312920496  NOTICE: -->Python Interpreter Initialized<--
11:24:09 T:1952514048   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/
11:24:09 T:1952514048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
11:24:09 T:1312920496  NOTICE: Thread BackgroundLoader start, auto delete: false
```

**Comment by ramonskie** [comment]
after a compleet reboot everything works again.

but it seems that the 0.4.2 version that is in the pulsar official repo is corrupted somehow

**Comment by inieto** [comment]
ramonskie, where did you download it from?
I'm stuck on "restarting xbmc for pulsar daemon to start" and I'm not being able to see logs (activated debugging but can't find logs with kodi's file manager"
Thanks!

**Comment by ramonskie** [comment]
from the releases page
https://github.com/steeve/plugin.video.pulsar/releases
